core/apps/accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path("profile/", views.ProfileView.as_view(), name="profile"),
]

core/apps/core/urls.py
from django.urls import path
from core import views


app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

core/myapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("core.urls")),
    path("publications/", include("publications.urls")),
]

core/apps/core/models/base.py
import uuid
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext, ugettext_lazy as _
from accounts.models import get_sentinel_user


class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET(
            get_sentinel_user
        ),  # if the related user is deleted, sets the creator to the "deleted" user!
        related_name="%(app_label)s_%(class)ss_as_owner",
        related_query_name="%(app_label)s_%(class)s_as_owner",
        verbose_name=_("owner"),
        help_text=_("Owner of this very object."),
        limit_choices_to={"is_active": True},
    )

    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_("creation date")
    )

    changed_at = models.DateTimeField(auto_now=True, verbose_name=_("update date"))

    metadata = models.JSONField(default=dict, blank=True)

    class Meta:
        abstract = True
        ordering = ["-changed_at"]

    def __str__(self):
        return str(self.id)

    def save(self, *args, **kwargs):
        if self.metadata is None:
            self.metadata = {}
        super(BaseModel, self).save(*args, **kwargs)

    def get_created_by(self):
        return self.history.earliest().history_user

    get_created_by.short_description = _("created by")
    created_by = property(get_created_by)

    def get_changed_by(self):
        return self.history.latest().history_user

    get_changed_by.short_description = _("changed by")
    changed_by = property(get_changed_by)

core/apps/core/models/site.py
from django.conf import settings
from django.contrib.sites.models import Site
from django.db import models
from django.utils.translation import ugettext, ugettext_lazy as _
from publications.models import Image


class SiteCustomization(models.Model):
    # history = HistoricalRecords()  # done in translation.py

    site = models.OneToOneField(
        Site,
        on_delete=models.CASCADE,  # if Site is deleted, SiteCustomization will also be deleted!
        primary_key=True,
        verbose_name=_("site"),
    )

    is_open_for_signup = models.BooleanField(
        default=True, verbose_name=_("is open for signup")
    )

    tagline = models.CharField(  # [i18n]
        blank=True,
        max_length=settings.CORE_SITECUSTOMIZATION_TAGLINE_LENGHT,
        verbose_name=_("tagline"),
        help_text=_("A few words to describe this very website."),
        default="A few words to describe this very website.",
    )

    description = models.TextField(  # [i18n]
        blank=True,
        max_length=settings.CORE_SITECUSTOMIZATION_DESCRIPTION_LENGHT,
        verbose_name=_("description"),
        help_text=_("A short text to describe this very website."),
        default=_("A short text to describe this very website."),
    )

    image = models.ForeignKey(
        Image,
        blank=True,
        null=True,
        verbose_name=_("featured image"),
        on_delete=models.SET_NULL,
    )

    class Meta:
        verbose_name = _("site customization")
        verbose_name_plural = _("site customizations")
        ordering = ["site"]

    def __str__(self):
        return self.site.name if self.site.name else str(_("unknown"))

    def save(self, *args, **kwargs):
        super(SiteCustomization, self).save(*args, **kwargs)

        # Clear cached content
        Site.objects.clear_cache()

    @property
    def fontawesome_site_icon(self):
        return settings.FONTAWESOME_SITE_ICON

core/apps/publications/models/base.py
from core.models import BaseModel as CoreBaseModel


class BaseModel(CoreBaseModel):
    class Meta(CoreBaseModel.Meta):
        abstract = True

core/apps/core/views/base.py
from django.utils.translation import ugettext, ugettext_lazy as _
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "core/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object"] = {"title": _("Home")}
        return context

core/apps/core/templates/core/nav/accounts_menu.html
{% load i18n %}
<div class="navbar-item has-dropdown is-hoverable">
    <a class="navbar-link has-text-primary">
        {% if user.get_avatar_url %}
        <figure class="image is-24x24">
            <img class="is-rounded" src="{{ user.get_avatar_url }}">
        </figure>
        {% else %}
        <span class="icon">
            <i class="fas fa-lg fa-user"></i>
        </span>
        {% endif %}
    </a>
    <div class="navbar-dropdown is-right">
        {% if user.is_staff %}
        <a class="navbar-item" href="{% url 'admin:index' %}">{% trans 'Admin' %}</a>
        <hr class="navbar-divider">
        {% endif %}
        {% url 'accounts:profile' as the_url %}
        <a class="navbar-item" href="{{ the_url }}">{% trans 'Profile of' %} {{ user }}</a>
        {% url 'account_email' as the_url %}
        <a class="navbar-item{% if request.path == the_url %} is-active{% endif %}" href="{{ the_url }}">{% trans 'E-mail Addresses' %}</a>
        {% url 'socialaccount_connections' as the_url %}
        <a class="navbar-item{% if request.path == the_url %} is-active{% endif %}" href="{{ the_url }}">{% trans 'Account Connections' %}</a>
        {% url 'account_change_password' as the_url %}
        <a class="navbar-item{% if request.path == the_url %} is-active{% endif %}" href="{{ the_url }}">{% trans 'Change my password' %}</a>
        <hr class="navbar-divider">
        {% url 'account_logout' as the_url %}
        <a class="navbar-item{% if request.path == the_url %} is-active{% endif %}" href="{{ the_url }}">{% trans 'Sign Out' %}</a>
    </div>
</div>

core/apps/core/templates/core/nav/aside_menu.html
<p class="menu-label">
    <span class="icon-text">
        <span class="icon">
            <i class="{{ menu.icon }}"></i>
        </span>
        <span>{{ menu.title }}</span>
    </span>
</p>
<ul class="menu-list">
    {% for item in menu.items %}
    <li>
        <a href="{{ item.url }}" {% if item.active %} class="is-active" {% endif %}>
            <span class="icon-text">
                <span class="icon">
                    <i class="{{ item.icon }}"></i>
                </span>
                <span>{{ item.text }}</span>
            </span>
        </a>
    </li>
    {% endfor %}
</ul>

core/apps/core/templates/core/nav/base.html
{% load i18n %}
<nav class="navbar has-shadow is-spaced">
    <div class="container">
        {% include 'core/nav/brand.html' %}
        <div class="navbar-menu" id="navMenu">
            <div class="navbar-start">
                {% include 'myapp/nav/menu.html' %}
            </div>
            <div class="navbar-end">
                {% include 'core/nav/lang.html' %}
                {% if user.is_authenticated %}
                {% include 'core/nav/accounts_menu.html' %}
                {% else %}
                {% include 'core/nav/login_buttons.html' %}
                {% endif %}
            </div>
        </div>
    </div>
</nav>

core/apps/core/templates/core/nav/brand.html
<div class="navbar-brand">
    <a class="navbar-item" href="{% url 'core:home' %}">
        <div class="is-size-4 has-text-weight-bold is-family-secondary">
            <span class="icon">
                <i class="{{ request.site.sitecustomization.fontawesome_site_icon }}"></i>
            </span>
            <span>{{ request.site.name }}</span>
        </div>
    </a>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navMenu">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
    </a>
</div>

core/apps/core/templates/core/nav/lang.html
{% load i18n %}
<div class="navbar-item">
    <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link has-text-primary">
            <span class="icon">
                <i class="fas fa-lg fa-language"></i>
            </span>
        </a>
        <div class="navbar-dropdown is-right">
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
            <form action="{% url 'set_language' %}" method="post" class="navbar-item">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ request.path }}">
                <input name="language" type="hidden" value="{{ language.code }}">
                <input class="button is-primary is-fullwidth{% if language.code != LANGUAGE_CODE %} is-light{% endif %}" type="submit" value="{{ language.name_local }}">
            </form>
            {% endfor %}
        </div>
    </div>
</div>

core/apps/core/templates/core/nav/login_buttons.html
{% load i18n %}
<div class="navbar-item">
    <div class="buttons">
        {% url 'account_login' as the_url %}
        {% if request.path != the_url %}
        <a class="button is-primary is-outlined" href="{{ the_url }}">{% trans 'Log in' %}</a>
        {% endif %}

        {% if request.site.sitecustomization.is_open_for_signup %}
        {% url 'account_signup' as the_url %}
        {% if request.path != the_url %}
        <a class="button is-primary" href="{{ the_url }}">{% trans 'Signup' %}</a>
        {% endif %}
        {% endif %}
    </div>
</div>

core/apps/core/templates/core/nav/logout_button.html
{% load i18n %}
<div class="navbar-item">
    <div class="buttons">
        {% url 'account_logout' as the_url %}
        {% if request.path != the_url %}
        <a class="button is-primary is-outlined" href="{{ the_url }}">{% trans 'Sign Out' %}</a>
        {% endif %}
    </div>
</div>