core/apps/publications/urls.py
from django.urls import path, re_path
from publications import views


app_name = "publications"

# https://stackoverflow.com/questions/14351048/django-optional-url-parameters
# https://stackoverflow.com/questions/2325433/making-a-regex-django-url-token-optional
REGEX = r"(?P<pk>[\w]+)/(?:(?P<slug>[\w-]+)/)?"

urlpatterns = [
    path(
        "create/article/",
        views.ArticleCreateView.as_view(),
        name="article-create",
    ),
    path(
        "update/article/<str:pk>/",
        views.ArticleUpdateView.as_view(),
        name="article-update",
    ),
    path(
        "create/tutorial/",
        views.TutorialCreateView.as_view(),
        name="tutorial-create",
    ),
    path(
        "update/tutorial/<str:pk>/",
        views.TutorialUpdateView.as_view(),
        name="tutorial-update",
    ),
    path(
        "create/image/",
        views.ImageCreateView.as_view(),
        name="image-create",
    ),
    path(
        "update/image/<str:pk>/",
        views.ImageUpdateView.as_view(),
        name="image-update",
    ),
    path(
        "delete/<str:pk>/",
        views.PublicationDeleteView.as_view(),
        name="publication-delete",
    ),
    path(
        "",
        views.PublicationListView.as_view(),
        name="publication-list",
    ),
    re_path(
        r"^{}".format(REGEX),
        views.PublicationDetailView.as_view(),
        name="publication-detail",
    ),
]

core/myapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("core.urls")),
    path("publications/", include("publications.urls")),
]

core/templates/myapp/nav/menu.html
{% url 'publications:publication-list' as the_url %}
<div class="navbar-item has-dropdown is-hoverable">
    <a class="navbar-link{% if request.path == the_url %} is-active{% endif %}">
        <span class="icon mr-1">
            <i class="{{ publication_menu.icon }}"></i>
        </span>
        <span>{{ publication_menu.title }}</span>
    </a>

    <div class="navbar-dropdown">
        {% for item in publication_menu.items %}
        <a class="navbar-item" href="{{ item.url }}">
            <span class="icon mr-1">
                <i class="{{ item.icon }}"></i>
            </span>
            <span>{{ item.text }}</span>
        </a>
        {% endfor %}
    </div>
</div>